"""
Board Configuration - Auto-generated from manifest.json

This module is auto-generated from the board manifest and provides
hardware configuration to device scripts.

DO NOT EDIT THIS FILE MANUALLY - it will be overwritten!
Generate with: python3 generate_board_config.py manifest.json
"""

import network

class BoardConfig:
    """Board configuration for SCRIPTO_P4"""
    
    # Identity
    ID = "scripto_p4"
    NAME = "Scripto P4"
    VENDOR = "scripto"
    CHIP = "ESP32-P4"
    REVISION = "2.0.1"
    DESCRIPTION = "ESP32-P4 development board with Ethernet, CAN, and NeoPixel status LED"
    
    # Network configuration
    HOSTNAME_PATTERN = "pyDirect-{mac_suffix}"
    MDNS_ENABLED = True
    AP_SSID_PATTERN = "pyDirect-{mac_suffix}"
    AP_PASSWORD = None
    DEFAULT_SERVICES = ["http", "webrepl"]
    
    # Capabilities
    HAS_ETHERNET = True
    HAS_WIFI = True
    HAS_CAN = True
    HAS_SDCARD = True
    HAS_AUDIO = True
    HAS_NEOPIXEL = True
    HAS_STATUS_LED = True
    
    # Pin definitions
    PIN_STATUS_LED = 1
    PIN_BOOT = 35
    
    # UART pins
    UART_PRIMARY_TX = 37
    UART_PRIMARY_RX = 38
    
    # I2C pins
    I2C0_SDA = 7
    I2C0_SCL = 8
    
    # CAN pins
    CAN_TX = 20
    CAN_RX = 21
    
    # SD card pins
    SDCARD_CMD = 44
    SDCARD_CLK = 43
    SDCARD_D0 = 39
    SDCARD_D1 = 40
    SDCARD_D2 = 41
    SDCARD_D3 = 42
    
    # Ethernet configuration
    ETH_PHY = "IP101"
    ETH_INTERFACE = "rmii"
    ETH_PHY_ADDR = 1
    ETH_MDC = 31
    ETH_MDIO = 52
    ETH_RESET = 51
    
    # Status LED configuration
    STATUS_LED_TYPE = "neopixel"
    STATUS_LED_PIXEL_ORDER = "RGB"
    
    @classmethod
    def get_mac_suffix(cls):
        """Get last 4 characters of MAC address"""
        import network
        wlan = network.WLAN(network.STA_IF)
        mac = wlan.config('mac')
        return ''.join(f'{b:02x}' for b in mac[-2:])
    
    @classmethod
    def get_hostname(cls):
        """Get device hostname with MAC suffix"""
        mac_suffix = cls.get_mac_suffix()
        return cls.HOSTNAME_PATTERN.format(mac_suffix=mac_suffix)
    
    @classmethod
    def get_ap_ssid(cls):
        """Get AP SSID with MAC suffix"""
        mac_suffix = cls.get_mac_suffix()
        return cls.AP_SSID_PATTERN.format(mac_suffix=mac_suffix)
    
    @classmethod
    def get_mdns_services(cls):
        """Get list of mDNS services to advertise"""
        services = []
        if "http" in cls.DEFAULT_SERVICES:
            services.append(("_http", "_tcp", 80))
        if "webrepl" in cls.DEFAULT_SERVICES:
            services.append(("_webrepl", "_tcp", 80))
        return services

# Convenience function
def get_hostname():
    """Get device hostname"""
    return BoardConfig.get_hostname()

def get_ap_ssid():
    """Get AP SSID"""
    return BoardConfig.get_ap_ssid()
