"""
Board Configuration - Auto-generated from manifest.json

This module is auto-generated from the board manifest and provides
hardware configuration to device scripts.

DO NOT EDIT THIS FILE MANUALLY - it will be overwritten!
Generate with: python3 generate_board_config.py manifest.json
"""

import network

class BoardConfig:
    """Board configuration for ESP32-S3-N8R2"""
    
    # Identity
    ID = "esp32_s3_n8r2"
    NAME = "ESP32-S3-N8R2"
    VENDOR = "espressif"
    CHIP = "ESP32-S3"
    REVISION = "1.0.0"
    DESCRIPTION = "ESP32-S3 with 8MB flash, 2MB PSRAM, and RGB LED on GPIO48"
    
    # Network configuration
    HOSTNAME_PATTERN = "pyDirect-{mac_suffix}"
    MDNS_ENABLED = True
    AP_SSID_PATTERN = "pyDirect-{mac_suffix}"
    AP_PASSWORD = None
    DEFAULT_SERVICES = ["http", "webrepl"]
    
    # Capabilities
    HAS_WIFI = True
    HAS_BLUETOOTH = True
    HAS_NEOPIXEL = True
    HAS_STATUS_LED = True
    HAS_USB_OTG = True
    
    # Pin definitions
    PIN_STATUS_LED = 48
    PIN_BOOT = 0
    
    # UART pins
    UART_PRIMARY_TX = 43
    UART_PRIMARY_RX = 44
    
    # I2C pins
    I2C0_SDA = 8
    I2C0_SCL = 9
    
    # SPI pins
    SPI2_MOSI = 11
    SPI2_MISO = 13
    SPI2_SCLK = 12
    SPI2_CS = 10
    
    # USB pins
    USB_DM = 19
    USB_DP = 20
    
    # Status LED configuration
    STATUS_LED_TYPE = "neopixel"
    STATUS_LED_PIXEL_ORDER = "RGB"
    
    # Memory configuration
    FLASH_SIZE = "8MB"
    PSRAM_SIZE = "2MB"
    PSRAM_MODE = "octal"
    
    @classmethod
    def get_mac_suffix(cls):
        """Get last 4 characters of MAC address"""
        import network
        wlan = network.WLAN(network.STA_IF)
        mac = wlan.config('mac')
        return ''.join(f'{b:02x}' for b in mac[-2:])
    
    @classmethod
    def get_hostname(cls):
        """Get device hostname with MAC suffix"""
        mac_suffix = cls.get_mac_suffix()
        return cls.HOSTNAME_PATTERN.format(mac_suffix=mac_suffix)
    
    @classmethod
    def get_ap_ssid(cls):
        """Get AP SSID with MAC suffix"""
        mac_suffix = cls.get_mac_suffix()
        return cls.AP_SSID_PATTERN.format(mac_suffix=mac_suffix)
    
    @classmethod
    def get_mdns_services(cls):
        """Get list of mDNS services to advertise"""
        services = []
        if "http" in cls.DEFAULT_SERVICES:
            services.append(("_http", "_tcp", 80))
        if "webrepl" in cls.DEFAULT_SERVICES:
            services.append(("_webrepl", "_tcp", 80))
        return services

# Convenience functions
def get_hostname():
    """Get device hostname"""
    return BoardConfig.get_hostname()

def get_ap_ssid():
    """Get AP SSID"""
    return BoardConfig.get_ap_ssid()
